# -*- mode: ruby -*-
# vi: set ft=ruby :

ENV['VAGRANT_I_KNOW_WHAT_IM_DOING_PLEASE_BE_QUIET'] = 'true' unless ENV['VAGRANT_INSTALLER_ENV']
ENV['VAGRANT_DEFAULT_PROVIDER'] = 'aws'

Vagrant.configure("2") do |config|
  # This doesn't work!
  # unless ENV['BUNDLE_BIN_PATH'] # avoid install when running under `bundle exec vagrant`
  #   config.vagrant.plugins = [{
  #     'vagrant-aws' => {
  #       :sources => 'https://rubygems.pkg.github.com/dweomer',
  #       :version => '~> 0.8.0.dweomer',
  #     }
  #   }]
  # end

  config.vm.synced_folder '.', '/vagrant', disabled: true

  %w[libvirt virtualbox].each do |p|
    config.vm.provider p do |v, o|
      v.memory = "2048"
      v.cpus = 2
      o.vm.box = 'centos/stream8'
    end
  end

  config.vm.provider :docker do |docker, override|
    docker.image = 'centos:8'
    docker.cmd = %w[tail -f /dev/null]
  end

  config.vm.provider :aws do |aws, override|
    aws.region = 'us-west-2'
    aws.ami = 'ami-056c679fab9e48d8a' # centos stream 8 x86_64
    aws.aws_profile = ENV['VAGRANT_AWS_PROFILE']
    aws.keypair_name = ENV['VAGRANT_AWS_KEYPAIR']
    override.ssh.username = 'centos'
    override.ssh.private_key_path = ENV['VAGRANT_AWS_PRIVATE_KEY_PATH'] || "#{ENV['HOME']}/.ssh/id_rsa"
  end
end
